### ISSUE TITLE
When i run the code that shows the array

### ISSUE THREAD

**Issue by techjewel** [jklz/DHL-API-Tracking-PHP#1]
Hi, when i run the code in my server without modifying anything that shows some error, Please check
http://hellojewel.net/dhl/example.php
This shows the array form the file.
So how i can solve this issue and track the shipping of DHL.

Thanks

**Comment by jklz** [comment]
You need to pass a tracking number to the request for it to work.

**Comment by ghost** [comment]
what does the $track->setAuth("*******_", "**_*****"); refer too?
